In [2]:
# NUMPYSCRIPT 
# Numpy is the most fundamental 

In [3]:
import numpy as np 

In [16]:
x = np.array([1,2,3])
print(x) 

# check for the type 
print("The type is ", type(x)) 

# check the shape of the array 
print("The shape is ", x.shape) # three elements arranged in a one dimensional array 

# Check the size 
print("Total size is ", x.size) 

# What is the dimension of the array 
print("The dimension of our array is ", x.ndim) 

# what is the data type 
print("The data type of elements is ", x.dtype) 

# what is the memory consumption 
print("It consumes ", x.nbytes, "bytes") 

[1 2 3]
The type is  <class 'numpy.ndarray'>
The shape is  (3,)
Total size is  3
The dimension of our array is  1
The data type of elements is  int64
It consumes  24 bytes


In [18]:
x = np.array([[1,2,3], [4, 5, 6]])
print(x) 

# check for the type 
print("The type is ", type(x)) 

# check the shape of the array 
print("The shape is ", x.shape) # three elements arranged in a one dimensional array 

# Check the size 
print("Total size is ", x.size) 

# What is the dimension of the array 
print("The dimension of our array is ", x.ndim) 

# what is the data type 
print("The data type of elements is ", x.dtype) 

# what is the memory consumption 
print("It consumes ", x.nbytes, "bytes") 

[[1 2 3]
 [4 5 6]]
The type is  <class 'numpy.ndarray'>
The shape is  (2, 3)
Total size is  6
The dimension of our array is  2
The data type of elements is  int64
It consumes  48 bytes


In [42]:
# We can switch data types to float, complex and unit 

a = np.array([[1, 2, 3], [4, 5, 6]], dtype = np.float64) 
print(a) 

b =  np.array([[1,2,3],[4,5,6]], dtype = np.complex128)
print(b) 

c = np.array([[1, 2, 3], [4, -5, 6]], dtype=np.int64)
print(c) 
print(c.nbytes) 


[[1. 2. 3.]
 [4. 5. 6.]]
[[1.+0.j 2.+0.j 3.+0.j]
 [4.+0.j 5.+0.j 6.+0.j]]
[[ 1  2  3]
 [ 4 -5  6]]
48


In [ ]:
# NUMPY ARRAYS OPERATIONS 